version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "8080:5000"
    volumes:
      - pdf_uploads:/app/uploads
      - pdf_outputs:/app/outputs
    environment:
      - SECRET_KEY=dev_key_for_testing
      - SESSION_COOKIE_SECURE=false  # Set to true if using HTTPS
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pdf_uploads:
  pdf_outputs: 